config/routes.rb
Voxfifa::Application.routes.draw do
  if Rails.env == 'production'
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end

  root :to => "home#index"
  resources :players
  resources :matches
  match 'rules' => 'rules#show'
  

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :home_player, :foreign_key => 'home_player_id', :class_name => 'Player'
  belongs_to :away_player, :foreign_key => 'away_player_id', :class_name => 'Player'

  attr_accessible :home_player_id, :home_team, :away_player_id, 
    :away_team, :home_score, :away_score, :reported_by,
    :game_date, :game_status

  validates :home_player_id, :presence => true
  validates :away_player_id, :presence => true
  validates :game_status, :presence => true
  validate :did_not_play_self

  def did_not_play_self
    if home_player == away_player
      errors[:base] << "You cannot play yourself"
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true
  has_many :home_matches, :class_name => "Match", :foreign_key => "home_player_id"
  has_many :away_matches, :class_name => "Match", :foreign_key => "away_player_id"

  def all_matches
    Match.where("away_player_id = ? or home_player_id = ?", id, id)
  end
end

app/models/standing.rb
class Standing

  def initialize(player)
    @player = Player.find(player)
  end

  def player
    @player
  end

  def wins
    win_count = 0
    player.all_matches.each do |match|
      if match.home_score && match.away_score
        if (match.home_player_id == player.id && match.home_score > match.away_score) ||
           (match.away_player_id == player.id && match.away_score > match.home_score)
          win_count = win_count + 1
        end
      end
    end

    win_count
  end

  def losses
    loss_count = 0
    player.all_matches.each do |match|
      if match.home_score && match.away_score
        if (match.home_player_id == player.id && match.home_score < match.away_score) ||
           (match.away_player_id == player.id && match.away_score < match.home_score)
          loss_count = loss_count + 1
        end
      end
    end

    loss_count
  end

  def ties
    tie_count = 0
    player.all_matches.each do |match|
      if match.home_score && match.away_score
        if match.home_score == match.away_score
          tie_count = tie_count + 1
        end
      end
    end

    tie_count
  end

  def points
    (wins * 3) + (ties * 1)
  end

  def goals_scored
    goal_count = 0
    player.all_matches.each do |match|
      if match.home_score && match.away_score
        if match.home_player_id == player.id
          goal_count += match.home_score
        elsif match.away_player_id == player.id
          goal_count += match.away_score
        end
      end
    end

    goal_count
  end

  def goals_allowed
    goal_count = 0
    player.all_matches.each do |match|
      if match.home_score && match.away_score
        if match.home_player_id == player.id
          goal_count += match.away_score
        elsif match.away_player_id == player.id
          goal_count += match.home_score
        end
      end
    end

    goal_count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable,
    :rememberable, :trackable, :validatable, :registerable 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :reported_matches, :class_name => 'Match', :foreign_key => 'reported_by'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @standings = []
    players = Player.all
    players.each do |player|
      @standings << Standing.new(player.id)
    end

    # sort by points descending
    @standings.sort! do |a,b|
      comp = (b.points <=> a.points)
      comp.zero? ? ((b.goals_scored - b.goals_allowed) <=> (a.goals_scored - a.goals_allowed)) : comp
    end

    @matches = Match.order("created_at DESC")
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @matches = Match.all
  end

  def new
    @match = Match.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  def create
    @match = Match.new(params[:match])
    @match.game_status = 'pre'
    respond_to do |format|
      if @match.save
        format.html { redirect_to(@match,
                      :notice => 'Match was successfully created.') }
        format.json { render :json => @match,
                      :status => :created, :location => @match }
      else
        format.html { render :action => "new" }
        format.json { render :json => @match.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    @match.game_status = 'final'
    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html  { redirect_to(@match,
                      :notice => 'Match was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @match.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @post }
    end
  end

  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html  { redirect_to(@player,
                      :notice => 'Player was successfully created.') }
        format.json  { render :json => @player,
                      :status => :created, :location => @player }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @player.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html  { redirect_to(@player,
                      :notice => 'Player was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @player.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Standings</h2>
<table width="50%" class="table table-striped">
  <thead>
    <tr>
      <th>Player</th>
      <th>W</th>
      <th>L</th>
      <th>T</th>
      <th>Pts</th>
      <th>GS</th>
      <th>GA</th>
    </tr>
  </thead>
  <tbody>
    <% @standings.each do |standing| %>
    <tr>
      <td><%= standing.player.name %></td>
      <td><%= standing.wins %></td>
      <td><%= standing.losses %></td>
      <td><%= standing.ties %></td>
      <td><%= standing.points %></td>
      <td><%= standing.goals_scored %></td>
      <td><%= standing.goals_allowed %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>Recent Matches</h2>
<table width="50%" class="table table-striped">
  <thead>
    <tr>
      <th>Home</th>
      <th>Score</th>
      <th>Away</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.where(:game_status => 'final').order("updated_at DESC").limit(5).each do |match| %>
    <tr>
      <td><%= match.home_player.name %> (<%= match.home_team %>)</td>
      <td><%= match.home_score %> - <%= match.away_score %></td>
      <td><%= match.away_player.name %> (<%= match.away_team %>)</td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>Upcoming Matches</h2>
<table width="50%" class="table table-striped">
  <thead>
    <tr>
      <th>Home</th>
      <th>Away</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.where(:game_status => 'pre').limit(5).each do |match| %>
    <tr>
      <td><%= match.home_player.name %></td>
      <td><%= match.away_player.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <%= link_to('Players', players_path) %>
  </li>
  <li>
    <%= link_to('Matches', matches_path) %>
  </li>
  <li>
    <%= link_to('Rules', rules_path) %>
  </li>
</ul>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li class="navbar-text">
      <%= current_user.email %>
    </li>
    <li>
      <%= link_to('Edit', edit_user_registration_path) %>
    </li>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
      <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
    <li>
      <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VOX FIFA" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <h1>VOX FIFA</h1>
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <% @match.errors.full_messages.each do |msg| %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>  
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <%= f.label :home_player %>
  <%= f.collection_select :home_player_id, Player.all, :id, :name %>

  <%= f.label :home_team %>
  <%= f.text_field :home_team %>

  <%= f.label :home_score %>
  <%= f.text_field :home_score %>

  <%= f.label :away_player %>
  <%= f.collection_select :away_player_id, Player.all, :id, :name %>

  <%= f.label :away_team %>
  <%= f.text_field :away_team %>

  <%= f.label :away_score %>
  <%= f.text_field :away_score %>

  <%= f.submit %>
<% end %>

app/views/matches/edit.html.erb
<h2>Editing match</h2>
 
<%= render 'form' %>
 
<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h2>Matches</h2>
<table width="50%" class="table table-striped">
  <thead>
    <tr>
      <th>Home</th>
      <th>Score</th>
      <th>Away</th>
      <th>Game Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @matches.count > 0 %>
      <% @matches.each do |match| %>
      <tr>
        <td><%= match.home_player.name %> (<%= match.home_team %>)</td>
        <td><%= match.home_score %> - <%= match.away_score %></td>
        <td><%= match.away_player.name %> (<%= match.away_team %>)</td>
        <td><%= match.game_status %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
      </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">NO MATCHES IN THE SYSTEM</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Match', new_match_path %>

app/views/matches/new.html.erb
<h2>New Match</h2>
<%= render 'form' %>


<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<h2>Match</h2>
<table class="table">
  <thead>
    <tr>
      <th>Home</th>
      <th>Score</th>
      <th>Away</th>
      <th>Game Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @match.home_player.name %> (<%= @match.home_team %>)</td>
      <td><%= @match.home_score %> - <%= @match.away_score %></td>
      <td><%= @match.away_player.name %> (<%= @match.away_team %>)</td>
      <td><%= @match.game_status %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_match_path(@match) %> | 
<%= link_to 'Delete', @match, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Add', new_match_path %> |
<%= link_to 'List', matches_path %>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <% @player.errors.full_messages.each do |msg| %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>  
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/players/edit.html.erb
<h2>Editing player</h2>
 
<%= render 'form' %>
 
<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h2>Players</h2>
<table width="50%" class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @players.count > 0 %>
      <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
      </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="2">NO PLAYERS IN THE SYSTEM</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Player', new_player_path %>

app/views/players/new.html.erb
<h2>New Player</h2>
<%= render 'form' %>


<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<h2>Player</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @player.name %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_player_path(@player) %> | 
<%= link_to 'Delete', @player, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Add', new_player_path %> |
<%= link_to 'List', players_path %>

app/views/rules/show.html.erb
<h2>Rules</h2>
<h3>Updated 10/23/2012</h3>
<ul>
  <li>Please acknowledge verbally that you are playing a league game before kickoff.</li>
  <li>
    <strong>Half Length:</strong> 8 minutes
  </li>
  <li>
    <strong>Teams:</strong> Player's discretion
  </li>
  <li>
    <strong>Weather:</strong> Player's discretion, clear or overcast suggested (rain sucks, snow is broken)
  </li>
  <li>
    <strong>Time of Day:</strong> Player's discretion, night suggested (no shadows!)
  </li>
  <li>
    <strong>All other concerns:</strong> Ask Hainesy.
  </li>
</ul>